services:
  nexus:
    container_name: nexus
    image: sonatype/nexus3
    ports:
      - "8081:8081"
    restart: unless-stopped
    environment:
      - NEXUS_CONTEXT=nexus
    volumes:
      - nexus-data:/nexus-data
    networks:
      nexus:
volumes:
  nexus-data:
    external: true
networks:
  nexus:
    external: true
